# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-deploy:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: circleci/openjdk:8
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: mvn install 
          command: |
            mvn -gs settings.xml clean install  
      - run:
          name: print
          command: |
            cat target/classes/git.properties 
            GIT_HASH=$(cat target/classes/git.properties | grep 'git.commit.id.abbrev' | cut -d'=' -f2)    
      - run:
          name: Build and Deploy
          command: |
            # mvn -gs settings.xml deploy
            mvn deploy:deploy-file \
              -DgroupId=com.github \
              -DartifactId=sync-client \
              -Dversion=$GIT_HASH \

# Orchestrate jobs using workflow
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  Build-Deploy:
    jobs:
      - build-deploy
