
version: 2.1

jobs:
  build-deploy:

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout
      - run:
          name: Maven Install  
          command: |
            mvn -gs settings.xml versions:update-property -Dproperty=org.odkx.odk-rest-interface-version
            mvn -gs settings.xml clean install 
 
      - run:
          name: Set project version
          command: |
            # Read the git.properties file and set the version
            GIT_HASH=$(grep 'git.commit.id.abbrev' target/classes/git.properties | cut -d'=' -f2 | tr -d '[:space:]')
            BUILD_TIME=$(grep 'git.build.time' target/classes/git.properties | cut -d'=' -f2 | tr -d '[:space:]' | sed 's/[-:]//g')
            mvn versions:set -DnewVersion="1.0.0-${BUILD_TIME}-${GIT_HASH}"

      - run:
          name: Build and Deploy
          command: |
            mvn -gs settings.xml clean deploy
            
workflows:
  Build-Deploy:
    jobs:
      - build-deploy
